import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: "%s | Create Next App",
    default: "Default | Create Next App",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <footer>
          <Link href={"/"}>Home</Link>
          <Link href={"/parallel"}>Parallel</Link>
          <Link href={"/non-parallel"}>Non Parallel</Link>
        </footer>
      </body>
    </html>
  );
}
